// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVLwMku13PWhpEoIMuoH3orHObQPzSI-M',
    appId: '1:621498694112:web:0ec63e4b62704be2485385',
    messagingSenderId: '621498694112',
    projectId: 'project-guardian-enayman',
    authDomain: 'project-guardian-enayman.firebaseapp.com',
    storageBucket: 'project-guardian-enayman.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbeB8s7w9FU54DPT_xv-4MLO7MDlsZJJk',
    appId: '1:621498694112:android:86bcc4c8d4e19355485385',
    messagingSenderId: '621498694112',
    projectId: 'project-guardian-enayman',
    storageBucket: 'project-guardian-enayman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGcztZ0nx69bDgx0KiozBl-g9jv_YaiNk',
    appId: '1:621498694112:ios:5b32c4dca1711a8e485385',
    messagingSenderId: '621498694112',
    projectId: 'project-guardian-enayman',
    storageBucket: 'project-guardian-enayman.firebasestorage.app',
    iosBundleId: 'com.example.projectGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGcztZ0nx69bDgx0KiozBl-g9jv_YaiNk',
    appId: '1:621498694112:ios:5b32c4dca1711a8e485385',
    messagingSenderId: '621498694112',
    projectId: 'project-guardian-enayman',
    storageBucket: 'project-guardian-enayman.firebasestorage.app',
    iosBundleId: 'com.example.projectGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVLwMku13PWhpEoIMuoH3orHObQPzSI-M',
    appId: '1:621498694112:web:96efa36389310136485385',
    messagingSenderId: '621498694112',
    projectId: 'project-guardian-enayman',
    authDomain: 'project-guardian-enayman.firebaseapp.com',
    storageBucket: 'project-guardian-enayman.firebasestorage.app',
  );
}
